name: Generate RouterOS China IP Script

on:
  schedule:
    - cron: '0 2 * * *' # 每天UTC 2点执行，可根据需要调整
  workflow_dispatch:

jobs:
  generate-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download chnroutes.txt
        run: |
          curl -sSL -o chnroutes.txt https://raw.githubusercontent.com/misakaio/chnroutes2/refs/heads/master/chnroutes.txt

      - name: Generate RouterOS script
        run: |
          GATEWAY="pppoe-out1"
          NOW=$(date "+%Y年 %m月%d日 %A %H时%M分%S秒 %Z")
          {
            echo "# RouterOS v7 中国 IP 路由表脚本"
            echo "# 生成时间: $NOW"
            echo "# 数据源: https://raw.githubusercontent.com/misakaio/chnroutes2/refs/heads/master/chnroutes.txt"
            echo "# 网关: $GATEWAY"
            echo "/ip route remove [find where comment~\"China Route\"]"
            echo "/ip route"
            awk -v gw="$GATEWAY" '$1 ~ /^#/ {next} {print "add dst-address="$1" gateway="gw" comment=\"China Route: "$1"\""}' chnroutes.txt
            echo "# 脚本结束"
            echo ":put \"中国 IP 路由已添加 (网关: $GATEWAY)\""
          } > routeros-china-ip.rsc

      - name: Commit and push if changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # 防止浅克隆导致推送失败
          git fetch --unshallow || true
          # 优先使用 GH_PAT，如果没有则用 GITHUB_TOKEN
          if [[ -n "$GH_PAT" ]]; then
            git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          else
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          fi
          # 避免推送冲突
          git pull --rebase || true
          if [[ -n $(git status --porcelain routeros-china-ip.rsc) ]]; then
            git add routeros-china-ip.rsc
            git commit -m "自动更新 RouterOS 中国 IP 路由表脚本"
            git push
          fi
